# Generated by Django 6.0.2 on 2026-02-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('adress', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
