# Generated by Django 6.0.2 on 2026-02-23 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(blank=True, max_length=50)),
                ('customermobile', models.CharField(max_length=50)),
                ('customeradress', models.TextField()),
            ],
            options={
                'verbose_name_plural': '7. Customer',
            },
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name_plural': '2. Unit'},
        ),
        migrations.AlterModelOptions(
            name='vender',
            options={'verbose_name_plural': '1. Vender'},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.unit')),
            ],
            options={
                'verbose_name_plural': '3. Product',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('totalamt', models.FloatField(default=0, editable=False)),
                ('purdate', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vender')),
            ],
            options={
                'verbose_name_plural': '4. Purchase',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('totalamt', models.FloatField(default=0, editable=False)),
                ('saledate', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
            options={
                'verbose_name_plural': '5. Sale',
            },
        ),
        migrations.CreateModel(
            name='Inventry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purqty', models.FloatField(default=0, null=True)),
                ('saleqty', models.FloatField(default=0, null=True)),
                ('totalbalqty', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('purchase', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.purchase')),
                ('sale', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sale')),
            ],
            options={
                'verbose_name_plural': '6. Inventry',
            },
        ),
    ]
